baseURL = "https://yinheio.github.io/"
title = "梦幻银河"
languageCode = "zh-CN"
hasCJKLanguage = true
theme = "Galaxy"
paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true
defaultLayout="posts" # DO NOT CHANGE IT
[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[taxonomies]
  category = "categories"
  tag = "tags"
  
[Permalinks]
 posts = "/:sections/:filename/"

[params]
    subtitle = "想象力才是终极生产力"  
	
[menu]

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/posts/about/"
    weight = 4

